kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "configuration.serviceAccountName" . }}
  labels: {{- include "configuration.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "pods"]
    verbs: ["patch", "get", "list"]

