{
 "title": "heketi dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": "label_values(heketi_device_brick_count, hostname)"
   },
   {
    "name": "device",
    "label": "device",
    "query": "label_values(heketi_device_brick_count, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "repeat": "hostname",
   "content": "# $hostname "
  },
  { "title": "Node", "type": "text", "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 }, "content": "# $hostname " },
  { "title": "Node", "type": "text", "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 }, "content": "# $hostname " },
  {
   "title": "device_brick_count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "repeat": "hostname",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_device_brick_count{hostname=~\"$hostname\", device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "device_brick_count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_device_brick_count{hostname=~\"$hostname\", device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "device_brick_count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_device_brick_count{hostname=~\"$hostname\", device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "block_device_usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "repeat": "hostname",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(heketi_device_used_bytes{hostname=~\"$hostname\", device=~\"$device\"} / heketi_device_size_bytes{hostname=~\"$hostname\", device=~\"$device\"}) * 100",
     "legendFormat": "{{` {{hostname}} / {{device}} `}}"
    }
   ]
  },
  {
   "title": "block_device_usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(heketi_device_used_bytes{hostname=~\"$hostname\", device=~\"$device\"} / heketi_device_size_bytes{hostname=~\"$hostname\", device=~\"$device\"}) * 100",
     "legendFormat": "{{` {{hostname}} / {{device}} `}}"
    }
   ]
  },
  {
   "title": "block_device_usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(heketi_device_used_bytes{hostname=~\"$hostname\", device=~\"$device\"} / heketi_device_size_bytes{hostname=~\"$hostname\", device=~\"$device\"}) * 100",
     "legendFormat": "{{` {{hostname}} / {{device}} `}}"
    }
   ]
  },
  {
   "title": "Device size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "repeat": "hostname",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_device_size_bytes{hostname=~\"$hostname\", device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Device size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_device_size_bytes{hostname=~\"$hostname\", device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Device size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_device_size_bytes{hostname=~\"$hostname\", device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "heketi_volumes_count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "heketi_volumes_count" }
   ]
  }
 ]
}