{
 "title": "All pods per namespace",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod!~\"cronjob.*\"}, pod)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\",container!=\"POD\", pod=~\"$pod\",node=~\"$node\"}[1m]))",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\",node=~\"$node\"})",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{job=\"kubelet\", pod=~\"$pod\",node=~\"$node\"}[1m])))",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  }
 ]
}