{{- if and .Values.networkPolicy.enabled (not .Values.global.isOpenshift | default false) }}
{{- if and (.Capabilities.APIVersions.Has "crd.projectcalico.org/v1") (ne .Values.global.clusterVisibility false) -}}
{{ include "exporting.calicoNetworkpolicy" . }}
{{- else if and (.Capabilities.APIVersions.Has "crd.projectcalico.org/v3") (ne .Values.global.clusterVisibility false) -}}
{{ include "exporting.calicoNetworkpolicy" . }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: exporting-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "exporting.name" . }}
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
            - 169.254.169.254/32
      - podSelector:
          matchLabels:
            app: api-gateway
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: zookeeper
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: mongodb
      - podSelector:
          matchLabels:
            app: configuration
      - podSelector:
          matchLabels:
            app: identity
      - podSelector:
          matchLabels:
            app: galaxy
      - podSelector:
          matchLabels:
            app: storage
      ports:
      - port: {{ .Values.networkPolicy.egress.ports.apiGateway }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.http }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.sslPort }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.mongodb }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.zookeeper }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.dnsPort }}
        protocol: UDP
      - port: {{ .Values.networkPolicy.egress.ports.configuration }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.rabbitmq }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.rabbitmq2 }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.identity }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.galaxy }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.storage }}
        protocol: TCP
      - port: {{ .Values.networkPolicy.egress.ports.exporterXlsx }}
        protocol: TCP
  policyTypes:
  - Egress
{{- end}}
{{- end }}
