{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "query.fullname" . }}
  labels:
    {{- include "query.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "query.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "query.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
