apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "oxygen.name" . }}
  labels: {{- include "oxygen.labels" . | nindent 4 }}
spec:
  replicas: {{ include "oxygen.replicas" . }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "oxygen.name" . }}
  template:
    metadata:
      labels: {{- include "oxygen.labels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "oxygen.serviceAccountName" . }}
      {{- if .Values.global.securityContext }}
      securityContext:
        runAsGroup: {{ .Values.global.securityContext.runAsGroup }}
        runAsUser: {{ .Values.global.securityContext.runAsUser }}
        fsGroup: {{ .Values.global.securityContext.fsGroup }}
      {{- if and ( (.Values.global.securityContext.seLinuxOptions).level ) ( not (.Values.global.isOpenshift | default false) ) }}
        seLinuxOptions:
          level: {{ .Values.global.securityContext.seLinuxOptions.level }}
      {{- end }}
      {{- else if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ include "oxygen.name" . }}
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.global.clusterMode.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-{{ .Release.Name }}-Application"
                operator: In
                values:
                - "true"
      {{- end }}
      containers:
      - env:
    {{- if .Values.global.securityContext }}
    {{- if ne (.Values.global.securityContext.runAsUser | toString) "1000" }}
        - name: HOME
          value: "/tmp"
    {{- end }}
    {{- else if .Values.securityContext.runAsUser }}
    {{- if ne (.Values.securityContext.runAsUser| toString) "1000" }} 
        - name: HOME
          value: "/tmp"
    {{- end }}
    {{- end }}
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: NAMESPACE_NAME
        - name: OXYGEN_IP
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: OXYGEN_HOST
        - name: SSL_ENABLED
          value: "{{ .Values.global.ssl.enabled }}"
        - name: NEW_RELIC_APP_NAME
          value: "oxygen"
        - name: SELS_URL
          value: "https://auth.cloud.sisense.com"
        - name: 'CONTAINER_MEMORY_LIMIT'
          valueFrom:
            resourceFieldRef:
              containerName: {{ template "oxygen.name" . }}
              resource: limits.memory
              divisor: '1Mi'
        - name: 'NODE_OPTIONS'
          value: "$(DEFAULT_NODE_OPTIONS) --max-old-space-size=$(CONTAINER_MEMORY_LIMIT)"
        envFrom:
        {{- if .Values.configMaps }}
        - configMapRef:
        {{- range .Values.configMaps }}
            name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.secrets }}
        - secretRef:
        {{- range .Values.secrets }}
            name: {{ . }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: global-configuration
        - configMapRef:
            name: apm-configuration
        name: {{ template "oxygen.name" . }}
        command:
          - "/bin/sh"
          - "-c"
          - >
             mkdir -p /opt/sisense/storage/licensing;
             npm start;
        image: "{{ .Values.global.imageRegistry }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - containerPort: 31112
          - containerPort: 8457
        resources:
          limits: 
            cpu: {{ include "oxygen.limits.cpu" . }}
            memory: {{ include "oxygen.limits.memory" . }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - mountPath: /opt/sisense/storage
          name: storage
        lifecycle:
          preStop:
            httpGet:
              path: prestop
              port: 31112
              scheme: HTTP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 31112
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 31112
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
    {{- if .Values.global.clusterMode.enabled }}
      - name: storage
        persistentVolumeClaim:
          claimName: "storage"
    {{- else }}
      - name: storage
        hostPath:
          path: /opt/sisense/storage
          type: DirectoryOrCreate
    {{- end }}
      restartPolicy: Always
      initContainers:
      - name: init-configuration
        image: "{{ .Values.global.imageRegistry }}/utilsbox:stable"
        command: ['sh', '-c', 'until nc -zv configuration.{{ .Release.Namespace }} 3030 -w1; do echo waiting for configuration; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "oxygen.name" . }}
  labels: {{- include "oxygen.labels" . | nindent 4 }}
spec:
 selector:
   app: {{ template "oxygen.name" . }}
 ports:
  - name: tcp
    protocol: TCP
    port: 31112
    targetPort: 31112
  - name: internal-http-rpc
    port: 8457
    protocol: TCP
    targetPort: 8457
