global:
  sisense_version: onyx.441
  build_connectors_image_tag: onyx.438
  connectors_image_tag: onyx.310
  monetdb_image_tag: onyx.413
  monetdb_v2_image_tag: onyx.310
  utils_image_tag: onyx.374
  external_kube_apiserver_address: ''
  applicationDnsName: ''
  clusterMode:
    enabled: true
  imageRegistry: quay.io/sisense
  imagePullSecrets: []
  gatewayPort: 30845
  ssl:
    enabled: false
  exposeNodePorts:
    enabled: false
  kubeNetworkPlugin: calico
  isKubernetesCloud: true
  kubernetesCloudProvider: aws
  highAvailability: true
  clusterVisibility: true
  vpnMode: false
  cloudLoadBalancer:
    enabled: true
    isInternal: false
  storageType: fsx
  storageClass: gp2
  serviceAccountAnnotations: {}
  enableWidgetDeltas: false
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    seLinuxOptions:
      level: s0:c123,c456
  isOpenshift: false
  offlineInstaller: false
  monitoring:
    internal: false
    external: false
  deploymentSize: small
  notifyOnUpgrade: true
  mongodb:
    enabled: true
  keda:
    enabled: false
  onyx:
    enabled: true
keda:
  enabled: false
  podSecurityContext:
    operator:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    metricServer:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    webhooks:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
  image:
    keda:
      repository: quay.io/sisense/keda
    metricsApiServer:
      repository: quay.io/sisense/keda-metrics-apiserver
    webhooks:
      repository: quay.io/sisense/keda-admission-webhooks
mongodb:
  enabled: true
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
  architecture: replicaset
  pdb:
    create: true
  metrics:
    enabled: false
    serviceMonitor:
      namespace: monitoring
zookeeper:
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
  configuration: 'tickTime=2000

    initLimit=10

    syncLimit=5

    dataDir=/bitnami/zookeeper/data

    clientPort=2181

    maxClientCnxns=1000

    autopurge.snapRetainCount=3

    autopurge.purgeInterval=1

    snapshot.trust.empty=true

    metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider

    metricsProvider.httpPort=9141

    metricsProvider.exportJvmInfo=true

    maxCnxns=0

    reconfigEnabled=false

    quorumListenOnAllIPs=false

    4lw.commands.whitelist=srvr, mntr, ruok

    maxSessionTimeout=40000

    server.1=onyx-zookeeper-0.onyx-zookeeper-headless.sisense.svc.cluster.local:2888:3888

    server.2=onyx-zookeeper-1.onyx-zookeeper-headless.sisense.svc.cluster.local:2888:3888

    server.3=onyx-zookeeper-2.onyx-zookeeper-headless.sisense.svc.cluster.local:2888:3888'
  replicaCount: 3
  pdb:
    maxUnavailable: 2
  metrics:
    enabled: false
rabbitmq:
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
  replicaCount: 3
  clustering:
    enabled: true
  metrics:
    enabled: false
grafana:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  adminUser: user-sisense
  adminPassword: passwd-sisense
  storageClassName: gp2
  initChownData:
    enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://sisense-prom-operator-kube-prometheus.monitoring:9090
        access: proxy
        isDefault: true
  sidecar:
    dashboards:
      searchNamespace: sisense
    datasources:
      searchNamespace: sisense
      createPrometheusReplicasDatasources: false
  grafana.ini:
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/nodes.json
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-sisense-Application
            operator: In
            values:
            - 'true'
sisense-utils:
  azureCsi:
    enabled: false
  azureDefaultDiskSize: 1200
  dbConnectionString: null
  email_sending_block: false
  fsxDnsName: fs-0f2d8df25494090f4.fsx.eu-west-1.amazonaws.com
  fsxMountName: ''
  internal_logs: true
  isManaged: false
  monitoring_namespace: monitoring
  resourceQuota:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 750Mi
  rwxScName: null
  sisenseDiskSize: 70
  timezone: UTC
cloud360:
  allowCloud360: false
  image:
    tag: onyx.374
usage:
  image:
    tag: onyx.417
  csv_path: /opt/sisense/storage/usage-service
  monitoring:
    image:
      tag: onyx.374
configuration:
  image:
    tag: onyx.439
reporting:
  image:
    tag: onyx.374
oxygen:
  image:
    tag: onyx.374
model-graphql:
  image:
    tag: personal-FEAT__ONYX-1262_JoinRecommendationsReset_onyx-e46392d
model-logspersistence:
  image:
    tag: personal-onyx-93bf18b
management:
  monetdb_image_tag: onyx.413
  monetdb_v2_image_tag: onyx.310
  utils_image_tag: onyx.374
  build_connectors_image_tag: onyx.467
  custom_code_image_tag: onyx.310
  image:
    tag: onyx.467
query:
  monetdb_image_tag: onyx.413
  monetdb_v2_image_tag: onyx.310
  utils_image_tag: onyx.374
  build_connectors_image_tag: onyx.438
  image:
    tag: onyx.438
build:
  monetdb_image_tag: onyx.413
  monetdb_v2_image_tag: onyx.310
  utils_image_tag: onyx.374
  build_connectors_image_tag: onyx.438
  custom_code_image_tag: onyx.310
  image:
    tag: onyx.438
translation:
  image:
    tag: onyx.310
analyticalengine:
  image:
    tag: onyx.374
connectors:
  image:
    tag: onyx.310
jobs:
  image:
    tag: onyx.374
identity:
  image:
    tag: personal-feature__ONYX-1466-64fe6ba
infusion:
  image:
    tag: onyx.374
galaxy:
  image:
    tag: onyx.317
  formula:
    image:
      tag: onyx.374
storage:
  image:
    tag: onyx.374
  git:
    enabled: true
    image:
      tag: onyx.374
pivot2-be:
  image:
    tag: onyx.374
exporter-xlsx:
  image:
    tag: onyx.374
plugins:
  image:
    tag: onyx.374
intelligence:
  image:
    tag: onyx.374
api-gateway:
  image:
    tag: onyx.441
customcode:
  image:
    tag: onyx.310
warehouse:
  image:
    tag: onyx.310
  warehouse_sels_url: https://sels.dec-staging.periscopedata.com
  warehouse_dec_id: us-west-2.dec-staging.sisense.com
  warehouse_dec_graphql_url: https://api-internal.dec-staging.periscopedata.com/graphql
compute-service:
  image:
    tag: onyx.374
external-plugins:
  image:
    tag: onyx.7
quest:
  image:
    tag: onyx.310
ai-integration:
  image:
    tag: onyx.574
migration:
  image:
    tag: onyx.430
monitoring:
  image:
    tag: onyx.374
exporting:
  image:
    tag: onyx.374
ai-services:
  image:
    tag: onyx.433
sisense-slack-service:
  image:
    tag: onyx.374
ms-teams-bot:
  imagei:
    tag: onyx.374
sisense-one:
  image:
    tag: onyx.374
admin-management:
  image:
    name: onyx-backend
    tag: onyx.403
dgraph:
  enabled: false
dgraph-ha:
  enabled: false
nlq-compile:
  enabled: false
nlq-duckling:
  enabled: false
nlq-rt:
  enabled: false
knowledgegraph:
  enabled: false
onyx-backend:
  image:
    tag: personal-fix__stringified-cors-fe8058d
