{{- $deploymentname := include "connectors.name" . }}
{{- $deployment := (lookup "apps/v1" "Deployment" .Release.Namespace $deploymentname ) }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connectors.serviceAccountName" . }}
  labels: {{- include "connectors.labels" . | nindent 4 }}
  {{- if or .Values.global.serviceAccountAnnotations .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.global.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}