{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filebrowser.serviceAccountName" . }}
  labels: {{- include "filebrowser.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.global.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
