{{- if .Values.serviceAccount.create -}}
{{- if not .Values.global.clusterMode.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dgraph.serviceAccountName" . }}
  labels: {{- include "dgraph.labels" . | nindent 4 }}
  {{- if or .Values.global.serviceAccountAnnotations .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.global.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
automountServiceAccountToken: false  
{{- end }}
{{- end }}
