{{- if .Values.global.clusterMode.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{ end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ template "api-gateway.name" . }}
  labels:
    app: {{ template "api-gateway.name" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "api-gateway.name" . }}
{{- end }}
