kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "api-gateway.fullname" . }}
  labels: {{- include "api-gateway.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "api-gateway.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "api-gateway.fullname" . }}
