kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "api-gateway.fullname" . }}
  labels: {{- include "api-gateway.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch", "create", "delete"]
  - apiGroups: [ "", "apps", "extensions" ]
    resources: [ "deployments" ]
    verbs: [ "patch", "get", "list" ]
