{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "compute.fullname" . }}
  namespace: {{ template "compute.namespace" . }}
  labels:
    {{- include "compute.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "compute.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "compute.serviceAccountName" . }}
  namespace: {{ template "compute.namespace" . }}
{{- end -}}
