kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "admin-management.serviceAccountName" . }}
  labels: {{- include "admin-management.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments"]
    verbs: ["patch", "get", "list"]

