{{- if .Values.global.clusterMode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}-headless
  labels: {{- include "dgraph-ha.labels" . | nindent 4 }}
    component: {{ .Values.alpha.name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: alpha-grpc-int
    port: 7080
    targetPort: 7080
  selector:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.alpha.name }}
    release: {{ .Release.Name }}
{{- end }}
