{{- if .Values.global.clusterMode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}
  labels: {{- include "dgraph-ha.labels" . | nindent 4 }}
    component: {{ .Values.alpha.name }}
spec:
  type: {{ .Values.alpha.service.type }}
  ports:
  - port: 8080
    targetPort: 8080
    name: alpha-http
  - port: 9080
    targetPort: 9080
    name: alpha-grpc
  selector:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.alpha.name }}
    release: {{ .Release.Name }}
{{- end }}
