kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "migration.name" . }}
  labels: {{- include "migration.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [ "", "apps", "extensions" ]
    resources: [ "deployments" ]
    verbs: [ "patch", "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ "system-user-token" ]
    verbs: [ "get", "watch", "list", "patch" ]

