{{- if and .Values.rbac.create (or .Values.global.clusterVisibility (not (hasKey .Values.global "clusterVisibility"))) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "management.fullname" . }}-clusterrolebinding
  labels:
    {{- include "management.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "management.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "management.fullname" . }}-visibility-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
