{{- if and .Values.rbac.create (or .Values.global.clusterVisibility (not (hasKey .Values.global "clusterVisibility"))) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "management.fullname" . }}-visibility-clusterrole
  labels: {{- include "management.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
{{- end -}}
