{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ec-bld-block-169-254-169-254
  namespace:  {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      plugin-script-runner: ec-bld-pod
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 169.254.169.254/32
{{- end }}