kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "usage.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "usage.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["system-user-token"]
    verbs: ["get", "watch", "list", "patch"]
