{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "usage.serviceAccountName" . }}
  labels: {{- include "usage.labels" . | nindent 4 }}
  {{- if or .Values.global.serviceAccountAnnotations .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.global.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
