{{- if .Values.allowCloud360 | default false }}
{{- if .Values.serviceAccount.create | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloud360.serviceAccountName" . }}
  labels: {{- include "cloud360.labels" . | nindent 4 }}
  {{- if or .Values.global.serviceAccountAnnotations .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.global.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
