apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "knowledgegraph.name" . }}
  labels: {{- include "knowledgegraph.labels" . | nindent 4 }}
    {{- if not ( (.Values.global.onyx).enabled | default false ) }}
    nlq: "true"
    {{- end }}
spec:
{{- if .Values.global.clusterMode.enabled }}
  replicas: 1
{{- else }}
  replicas: 1
{{- end }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- else if eq .Values.global.imageRegistry "docker.artifactory.sisense.com"}}
  strategy:
    type: Recreate
    rollingUpdate: null
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "knowledgegraph.name" . }}
      {{- if not ( (.Values.global.onyx).enabled | default false ) }}
      nlq: "true"
      {{- end }}
  template:
    metadata:
      labels: {{- include "knowledgegraph.labels" . | nindent 8 }}
        {{- if not ( (.Values.global.onyx).enabled | default false ) }}
        nlq: "true"
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "knowledgegraph.serviceAccountName" . }}
      {{- if .Values.global.securityContext }}
      securityContext:
        runAsGroup: {{ .Values.global.securityContext.runAsGroup }}
        runAsUser: {{ .Values.global.securityContext.runAsUser }}
        fsGroup: {{ .Values.global.securityContext.fsGroup }}
      {{- if and ( (.Values.global.securityContext.seLinuxOptions).level ) ( not (.Values.global.isOpenshift | default false) ) }}
        seLinuxOptions:
          level: {{ .Values.global.securityContext.seLinuxOptions.level }}
      {{- end }}
      {{- else if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.global.clusterMode.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-{{ .Release.Namespace }}-Application"
                operator: In
                values:
                - "true"
      {{- end }}
      containers:
      - env:
    {{- if .Values.global.securityContext }}
    {{- if ne (.Values.global.securityContext.runAsUser | toString) "1000" }}
        - name: HOME
          value: "/tmp"
        - name: UID
          value: {{ .Values.global.securityContext.runAsUser | quote }}
        - name: GID
          value: {{ .Values.global.securityContext.runAsGroup | quote }}
    {{- else }}
        - name: UID
          value: {{ .Values.global.securityContext.runAsUser | quote }}
        - name: GID
          value: {{ .Values.global.securityContext.runAsGroup  | quote }}     
    {{- end }}
    {{- else if .Values.securityContext.runAsUser }}
    {{- if ne (.Values.securityContext.runAsUser| toString) "1000" }}
        - name: HOME
          value: "/tmp"
        - name: UID
          value: {{ .Values.securityContext.runAsUser | quote }}
        - name: GID
          value: {{ .Values.securityContext.runAsGroup  | quote }}
    {{- else }}
        - name: UID
          value: {{ .Values.securityContext.runAsUser | quote }}
        - name: GID
          value: {{ .Values.securityContext.runAsGroup  | quote }}
    {{- end }}
    {{- end }}
        - name: PYTHONHASHSEED
          value: "0"
        - name: DEPLOYED_TIME
          valueFrom:
            configMapKeyRef:
              name: deployed-time
              key: deployed_time
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: RABBITMQ_CONN_STRING
        - name: ZOOKEEPER_URL
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: ZOOKEEPER_CONN_STRING
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: TZ
        - name: DGRAPH_URL
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: DGRAPH_URL
        - name: SERVICE_VERSION
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: SISENSE_VERSION
        - name: PYTHONUNBUFFERED
          value: "1"
        image: "{{ .Values.global.imageRegistry }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
        name: {{ template "knowledgegraph.name" . }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 9091
        resources:
          limits: 
            cpu: {{ include "knowledgegraph.limits.cpu" . }}
            memory: {{ include "knowledgegraph.limits.memory" . }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: Always
      initContainers:
      - name: init-configuration
        image: "{{ .Values.global.imageRegistry }}/utilsbox:stable"
        command: ['sh', '-c', 'until nc -zv configuration.{{ .Release.Namespace }} 3030 -w1; do echo waiting for configuration; sleep 2; done;']
      - name: init-dgraph
        image: "{{ .Values.global.imageRegistry }}/utilsbox:stable"
        env:
          - name: DGRAPH_URL
            valueFrom:
              configMapKeyRef:
                name: global-configuration
                key: DGRAPH_URL
        command: ['sh', '-c', 'until nc -zv ${DGRAPH_URL} 9080 -w1; do echo waiting for dgraph; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "knowledgegraph.name" . }}
  labels: {{- include "knowledgegraph.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "knowledgegraph.name" . }}
  ports:
  - name: {{ template "knowledgegraph.name" . }}
    port: 9091
    targetPort: 9091
