apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "galaxy.name" . }}
  labels: {{- include "galaxy.labels" . | nindent 4 }}
spec:
  replicas: {{ include "galaxy.replicas" . }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "galaxy.name" . }}
  template:
    metadata:
      labels: {{- include "galaxy.labels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "galaxy.serviceAccountName" . }}
      {{- if .Values.global.securityContext }}
      securityContext:
        runAsGroup: {{ .Values.global.securityContext.runAsGroup }}
        runAsUser: {{ .Values.global.securityContext.runAsUser }}
        fsGroup: {{ .Values.global.securityContext.fsGroup }}
      {{- if and ( (.Values.global.securityContext.seLinuxOptions).level ) ( not (.Values.global.isOpenshift | default false) ) }}
        seLinuxOptions:
          level: {{ .Values.global.securityContext.seLinuxOptions.level }}
      {{- end }}
      {{- else if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ include "galaxy.name" . }}
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.global.clusterMode.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-{{ .Release.Namespace }}-Application"
                operator: In
                values:
                - "true"
      {{- end }}
      containers:
      - env:
    {{- if .Values.global.securityContext }}
    {{- if ne (.Values.global.securityContext.runAsUser | toString) "1000" }}
        - name: HOME
          value: "/tmp"
    {{- end }}
    {{- else if .Values.securityContext.runAsUser }}
    {{- if ne (.Values.securityContext.runAsUser| toString) "1000" }} 
        - name: HOME
          value: "/tmp"
    {{- end }}
    {{- end }}
        - name: CSV_PATH
          value: "/opt/sisense/storage/usage/usage.csv"
        - name: NODE_EXTRA_CA_CERTS
          value: "/opt/sisense/storage/custom-certificates/ca-certificates.crt"
        - name: NEW_RELIC_APP_NAME
          value: "galaxy"
        - name: TRACKING_HOST
          value: "tracking.$(NAMESPACE_NAME)"
        - name: TRACKING_PORT
          value: "31114"
        - name: WEBSERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: REPORTING_HOST
        - name: GALAXY_PORT
          value: "16007"
        - name: ENABLE_WIDGET_DELTAS
          value: {{ .Values.global.enableWidgetDeltas | quote }}
        - name: CONTAINER_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: {{ template "galaxy.name" . }}
              resource: limits.memory
              divisor: '1Mi'
        - name: 'NODE_OPTIONS'
          value: "$(DEFAULT_NODE_OPTIONS) --max-old-space-size=$(CONTAINER_MEMORY_LIMIT)"

        envFrom:
        {{- if .Values.configMaps }}
        - configMapRef:
        {{- range .Values.configMaps }}
            name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.secrets }}
        - secretRef:
        {{- range .Values.secrets }}
            name: {{ . }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: global-configuration
        - configMapRef:
            name: apm-configuration
        image: "{{ .Values.global.imageRegistry }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: {{ template "galaxy.name" . }}
        resources:
          limits: 
            cpu: {{ include "galaxy.limits.cpu" . }}
            memory: {{ include "galaxy.limits.memory" . }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
{{ include "galaxy.container.command" . | indent 8 }}
        ports:
        - containerPort: 16007
        - containerPort: 8457
        lifecycle:
          preStop:
            httpGet:
              path: prestop
              port: 16007
              scheme: HTTP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 16007
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 16007
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /opt/sisense/storage
          name: storage
      - env:
    {{- if .Values.global.securityContext }}
    {{- if ne (.Values.global.securityContext.runAsUser | toString) "1000" }}
        - name: HOME
          value: "/tmp"
    {{- end }}
    {{- else if .Values.securityContext.runAsUser }}
    {{- if ne (.Values.securityContext.runAsUser| toString) "1000" }} 
        - name: HOME
          value: "/tmp"
    {{- end }}
    {{- end }}
        - name: NEW_RELIC_APP_NAME
          value: "formula-management"
        - name: FORMULA_MANAGEMENT_PORT
          value: "16010" # TODO: add OXYGEN_NEW_FLOW variable when default value is defined
        - name: INTERNAL_RPC_PORT
          value: "8458"
        - name: CONTAINER_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: {{ template "formula.name" . }}
              resource: limits.memory
              divisor: '1Mi'
        - name: 'NODE_OPTIONS'
          value: "$(DEFAULT_NODE_OPTIONS) --max-old-space-size=$(CONTAINER_MEMORY_LIMIT)"
        envFrom:
        {{- if .Values.configMaps }}
        - configMapRef:
        {{- range .Values.configMaps }}
            name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.secrets }}
        - secretRef:
        {{- range .Values.secrets }}
            name: {{ . }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: global-configuration
        - configMapRef:
            name: apm-configuration
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.formula.image.name }}:{{ .Values.formula.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: {{ template "formula.name" . }}
        resources:
{{ toYaml .Values.formula.resources | indent 12 }}  
        ports:
        - containerPort: 16010
        - containerPort: 8458
        lifecycle:
          preStop:
            httpGet:
              path: prestop
              port: 16010
              scheme: HTTP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 16010
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 16010
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /opt/sisense/storage
          name: storage
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
{{- if .Values.global.clusterMode.enabled }}
      - name: storage
        persistentVolumeClaim:
          claimName: storage
{{- else }}
      - name: storage
        hostPath:
          path: /opt/sisense/storage
          type: DirectoryOrCreate
{{- end }}
      restartPolicy: Always
      initContainers:
      - name: init-query
        image: "{{ .Values.global.imageRegistry }}/utilsbox:stable"
        command: ['sh', '-c', 'until nc -zv query.{{ .Release.Namespace }} 8082 -w1; do echo waiting for query; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "galaxy.name" . }}
  labels: {{- include "galaxy.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ template "galaxy.name" . }}
  ports:
  - name: tcp
    protocol: TCP
    port: 16007
    targetPort: 16007
  - name: internal-http-rpc
    port: 8457
    protocol: TCP
    targetPort: 8457

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "formula.name" . }}
  labels: {{- include "formula.serviceLabels" . | nindent 4 }}
spec:
  selector:
    app: {{ template "galaxy.name" . }}
  ports:
  - name: tcp
    protocol: TCP
    port: 16010
    targetPort: 16010
  - name: internal-http-rpc
    port: 8458
    protocol: TCP
    targetPort: 8458
