kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "galaxy.serviceAccountName" . }}
  labels: {{- include "galaxy.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "galaxy.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "galaxy.serviceAccountName" . }}
