# Default values

# replicaCount: 1
image:
  pullPolicy: IfNotPresent

serviceAccount: "migration"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  seLinuxOptions:
    level: "s0:c123,c456"
# If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
  # fsGroup: 1000

resources_small:
  limits:
    cpu: 1300m
    memory:  3.5Gi

resources_large:
  limits:
    cpu: 1300m
    memory: 8.5Gi

resources:
  # limits:
  #   cpu: 1500m
  #   memory: 8500Mi
  requests:
    cpu: 100m
    memory: 180Mi

## Pod topology spread constraints
## https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
## The value is evaluated as a template
topologySpreadConstraints: []

nodeSelector: {}

tolerations: []

podAnnotations: {}

# Referring to existing secrets and configMaps
secrets: []
configMaps: []

affinity: {}

## StrategyType
## Can be set to RollingUpdate or Recreate
updateStrategy: {}

keda:
  minReplicaCount: 2
  maxReplicaCount: 20
  stabilizationWindowSeconds: 300
  pollingInterval: 30
  scaleUpPercent: 50