{{- if and .Values.rbac.create (or .Values.global.clusterVisibility (not (hasKey .Values.global "clusterVisibility"))) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "validator.name" . }}-{{ .Release.Namespace }}
  labels: {{- include "validator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "validator.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "validator.name" . }}-{{ .Release.Namespace }}
{{- end -}}