kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "validator.name" . }}
data:
  functions.sh: |-
{{ .Files.Get "files/functions.sh" | indent 4}}
  run.sh: |-
{{ .Files.Get "files/run.sh" | indent 4}}
