kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "validator.name" . }}
  labels: {{- include "validator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "batch", "networking.k8s.io"]
    resources: ["jobs", "jobs/status", "ingresses", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods", "deployments","deployments/scale" , "configmaps"]
    verbs: ["get", "list", "watch", "patch", "scale"]

{{- $monitoring := (lookup "v1" "Namespace" "" "monitoring" ) }}
{{- if $monitoring }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "validator.name" . }}-{{ .Release.Namespace }}
  namespace: monitoring
  labels: {{- include "validator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "batch", "monitoring.coreos.com"]
    resources: ["jobs", "jobs/status", "prometheuses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "apps", "extensions"]
    resources: ["pods", "deployments", "deployments/scale", "configmaps"]
    verbs: ["get", "list", "watch", "patch", "scale"]
{{- end }}