{
 "title": "Zookeeper Overview",
 "description": "Dashboard for https://github.com/dabealu/zookeeper-exporter\r\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(jvm_info,job)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(jvm_info{job=~\"$job\"},namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values({job=~\"$job\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "leader_uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "leader_uptime{job=~\"$job\"}",
     "legendFormat": "{{` {{instance}} leader_uptime `}}"
    }
   ]
  },
  {
   "title": "Ephemerals Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "ephemerals_count{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Znode Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "znode_count{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "watch_count{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pakages Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(packets_sent{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  },
  {
   "title": "Pakages Recieved",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(packets_received{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_alive_connections{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "open_file_descriptor_count{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "open"
    },
    {
     "expr": "max_file_descriptor_count{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_latency{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  },
  {
   "title": "Min Latency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "min_latency{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_latency{job=~\"$job\", namespace=~\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_requests{job=~\"$job\", namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  },
  {
   "title": "Approx Data Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{` {{ pod }} `}}"
    }
   ]
  }
 ]
}