{
 "title": "Logging Dashboard",
 "description": "This is a simple dashboard for utilizing Fluent-bit and Fluentd",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   },
   {
    "name": "fluentdplugin",
    "label": "Fluentd Plugin",
    "query": "label_values(fluentd_output_status_emit_records, plugin_id)"
   },
   {
    "name": "fluentbit",
    "query": "label_values(fluentbit_input_bytes_total,pod)"
   },
   {
    "name": "fluentd",
    "query": "label_values(fluentd_output_status_emit_count,pod)"
   }
  ]
 },
 "panels": [
  { "title": "Aggregated Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fluent-bit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluent-bit.*\",cluster=\"$cluster\"})",
     "legendFormat": "Active Fluent-bit"
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluentd.*\",pod!~\".*config.*\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Fluentbit Input Record",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluentbit Output Records",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[1m]))"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(avg by (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", cluster=\"$cluster\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bad Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Fluentbit Input Bytes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[5m]))"
    }
   ]
  },
  {
   "title": "Fluentbit Output Bytes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[5m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "fluentd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Fluentd Records by Plugin",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_count{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[5m])",
     "legendFormat": "{{` {{ plugin_id }}/{{pod}} `}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Error and Retry",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[1m])) by (pod)",
     "legendFormat": "{{` Retry {{pod}} `}}"
    },
    {
     "expr": "sum(rate(fluentd_output_status_num_errors{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[1m])) by (pod)",
     "legendFormat": "{{` Error {{pod}} `}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Buffer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}",
     "legendFormat": "{{` {{ plugin_id }} `}}"
    },
    {
     "expr": "fluentd_output_status_buffer_queue_length{pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}"
    }
   ]
  },
  {
   "title": "Fluentd CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"sisense\", pod=~\".*fluentd.*\",pod!~\".*config.*\", cluster=\"$cluster\"}) by (pod)",
     "legendFormat": "{{` {{container}} `}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"sisense\", resource=\"cpu\", pod=~\".*fluentd.*\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"sisense\", resource=\"cpu\", pod=~\".*fluentd.*\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Fluentd Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"sisense\", pod=~\".*fluentd.*\", cluster=\"$cluster\"}) by (pod)",
     "legendFormat": "{{` {{ pod }} `}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"sisense\", resource=\"memory\", pod=~\".*fluentd.*\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "fluentbit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Fluent-Bit CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"sisense\", pod=~\".*fluent-bit.*\", cluster=\"$cluster\"}) by (pod)",
     "legendFormat": "{{` {{container}} `}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"sisense\", resource=\"cpu\", pod=~\".*fluent-bit.*\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"sisense\", resource=\"cpu\", pod=~\".*fluent-bit.*\"})\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Fluent-Bit Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"sisense\", pod=~\".*fluent-bit.*\"}) by (pod)",
     "legendFormat": "{{` {{pod}} `}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"sisense\", resource=\"memory\", pod=~\".*fluent-bit.*\"})\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"sisense\", resource=\"memory\", pod=~\".*fluent-bit.*\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Fluentbit Input Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{` {{ pod }}/{{name}} `}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{` {{ pod }}/{{name}} `}}"
    }
   ]
  },
  {
   "title": "Fluentbit Input Record",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{` {{ pod }}/{{name}} `}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Records",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{` {{ pod }}/{{name}} `}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Retries/Fails",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "{{` Retries {{ pod }}/{{name}} `}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "{{` Failed {{ pod }}/{{name}} `}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "{{` {{ pod }}/{{ name }} `}}"
    }
   ]
  }
 ]
}