apiVersion: v1
kind: Secret
metadata:
  name: infusion-secret
  namespace: {{ .Release.Namespace }}
  labels:
    component: infusion-service
    app.kubernetes.io/name: infusion-service
    app.kubernetes.io/instance: {{ .Release.Name }}  
data:
  token: {{ template "infusion.token" . }}