kind: ConfigMap
apiVersion: v1
metadata:
  name: apm-configuration
  labels: {{- include "sisense-utils.labels" . | nindent 4 }}
data:
  NEW_RELIC_NO_CONFIG_FILE: {{ .Values.apm.config.enabled | quote }}
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: {{ .Values.apm.distributed_tracing.enabled |  quote }}
  NEW_RELIC_ENABLED: {{ .Values.apm.enabled | quote }}
{{- if .Values.apm.enabled }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.apm.license| quote }}
  NEW_RELIC_LABELS: "version: {{ .Values.apm.sisense_version }}; display_name: {{ .Values.apm.process_host }}"
  NEW_RELIC_PROCESS_HOST_DISPLAY_NAME: {{ .Values.apm.process_host | quote }}
{{- end }}
