# {{- if .Capabilities.APIVersions.Has "policy/v1/PodSecurityPolicy" }}
# apiVersion: policy/v1
# {{ else }}
# apiVersion: policy/v1beta1
# {{ end -}}
# kind: PodSecurityPolicy
# metadata:
#   name: sisense-pcp
# spec:
#   privileged: false
#   allowPrivilegeEscalation: false
#   volumes:
#     - 'configMap'
#     - 'emptyDir'
#     - 'projected'
#     - 'secret'
#     - 'downwardAPI'
#     - 'persistentVolumeClaim'
#   hostNetwork: false
#   hostIPC: false
#   hostPID: false
#   runAsUser:
#     rule: 'MustRunAsNonRoot'
#     ranges:
#       - min: 1
#         max: 65535
#   seLinux:
#     rule: 'RunAsAny'
#   supplementalGroups:
#     rule: 'MustRunAs'
#     ranges:
#       - min: 1
#         max: 65535
#   fsGroup:
#     rule: 'MustRunAs'
#     ranges:
#       # Forbid adding the root group.
#       - min: 1
#         max: 65535
#   readOnlyRootFilesystem: false